$c->{base_version_long} = "EPrints 3.3.16";
$c->{base_version_alias} = "Gelato Blizzard";
$c->{base_vendor_long} = "EPrints Services";
$c->{base_vendor_short} = "eps";
$c->{version_long} = "ulcc-core 1.2";
$c->{version_alias} = "Year of the Whopper";
$c->{vendor_long} = "CoSector, University of London";
$c->{vendor_short} = "cs-uoL";
$c->{version_description} = $c->{base_version_long} ." (". $c->{base_version_alias} .") ". $c->{version_long} . " (" . $c->{version_alias} . ") (" . $c->{vendor_long} . ")";
