#!/usr/bin/perl

use EPrints;

use strict;

# New session
my $session = new EPrints::Session();
exit( 0 ) unless( defined $session );

if( !$session->current_user )
{
    $session->terminate;
    exit( 0 );
}

my $month = $session->param( "month" );

my $repoid = $session->{id};

my $html_file = "/var/www/monthly-reports/reports/$repoid/$month/index.html";

# Check if the file exists and is readable
if(-e $html_file && -r $html_file)
{
    # Open and read the file
    open my $fh, '<', $html_file or die "Cannot open file: $!";
    # Print the HTTP header and content
    $session->send_http_header( content_type => "text/html; charset=UTF-8" );

    binmode(STDOUT,":utf8");

    while( my $row = <$fh> )
    {
        chomp $row;
        print "$row\n";
    }

    close($fh);

    $session->terminate;
}
else
{
    $session->send_http_header( content_type => "text/html; charset=UTF-8" );

    binmode(STDOUT,":utf8");

    print "Report not found";

    $session->terminate;
}

exit 0;
